### PR TITLE
Add sleeps between core service starts

### PR DESCRIPTION
**Pull request by michaeltchapman**
Very high load is observable on all controllers during the second
step, when rabbit, redis and mongo are all started at once. This
can cause pacemaker heartbeat failures, ceph heartbeat failures,
high disk wait etc. leading to unpredictable failures in other
components.

### CODE REVIEW

**Comment by radez** [comment]
Curious if a full 15 seconds is necessary?
Not against it, just wonder what the logic is behind it.

**Comment by michaeltchapman** [comment]
After testing, I think it's really just mongo that's hogging cpu and causing timeouts for other things, and this change made no impact on that. I picked 15 seconds because that was roughly the duration of the period during which I could see no logging output, followed by a burst of activity.

**Comment by trozet** [comment]
@michaeltchapman "After testing, I think it's really just mongo that's hogging cpu and causing timeouts for other things, and this change made no impact on that."

Are you saying this patch needs more work to try to isolate mongodb?

**Comment by michaeltchapman** [comment]
@trozet Yep, this patch doesn't do anything useful at the moment, as far as I can tell. I started trying to get mongo cpu limited via cgroups on startup but I don't have that working yet.

**Pull request closed without merging**
