### PR TITLE
Add pcs cleanup exec

### PR DESCRIPTION
**Pull request by michaeltchapman**
Run a pcs cleanup before db sync and also at the end of the deployment.
This will give processes a chance to recover in case there has been
any kind of error that would lead to a process being scored -INFINITY
due to repeated failed startup that may have been caused by load during
the deployment, or another latent issue.

### CODE REVIEW

**Comment by trozet** [comment]
Cool.  Can you share the results you saw with this on your local setup?

**Comment by michaeltchapman** [comment]
Well it passed and all the services were up except congress, which is misconfigured atm, but that could be just because that particular run happened to work. I ran it locally more as a check that I wasn't putting up something that wouldn't compile. There's no logging that it had to restart anything - I could add something simple like write a line with the service name perhaps?

**Comment by trozet** [comment]
OK let's do a bunch of runs in CI and check for pcs failures other than congress at the end of hte deployment.  Finish the deployment with a warning message saying not all services are clean post-deployment.  Make sense?  Also, is there a bug filed to track the congress problem?

**Comment by michaeltchapman** [comment]
Congress issue is here: https://jira.opnfv.org/browse/APEX-206

**Pull request merged**
